# Generated by Django 5.0.6 on 2024-05-11 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account_detail',
            fields=[
                ('date_created', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('id_Number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('maritalStatus', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone_home', models.CharField(max_length=255)),
                ('phone_work', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('nok_name', models.CharField(max_length=255)),
                ('nok_relationship', models.CharField(max_length=25)),
                ('nok_phone', models.CharField(max_length=255)),
                ('nok_email', models.CharField(max_length=255, null=True)),
                ('nok_address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bank_account',
            fields=[
                ('account_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('balance_USD', models.FloatField()),
                ('balance_ZIG', models.FloatField()),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_api.account_detail')),
            ],
        ),
        migrations.CreateModel(
            name='account_transaction',
            fields=[
                ('date', models.DateField()),
                ('reference_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type_of_transaction', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=100)),
                ('usd_opening_balance', models.FloatField()),
                ('zig_balance', models.FloatField()),
                ('usd_closing_balance', models.FloatField()),
                ('zig_closing_balance', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_api.bank_account')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('Topic', models.CharField(max_length=255)),
                ('reply', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_api.account_detail')),
                ('reply_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('date', models.DateField()),
                ('reference_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=100)),
                ('sender_opening_balance', models.FloatField()),
                ('recipient_opening_balance', models.FloatField()),
                ('sender_closing_balance', models.FloatField()),
                ('recipient_closing_balance', models.FloatField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='payment_api.account_detail')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='payment_api.account_detail')),
            ],
        ),
    ]
