# Generated by Django 5.0.6 on 2024-05-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_detail',
            old_name='id_Number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='account_detail',
            old_name='maritalStatus',
            new_name='marital_status',
        ),
    ]
