# Generated by Django 5.0.6 on 2024-05-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0003_alter_transaction_recipient_alter_transaction_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(default='Gift', max_length=255),
        ),
    ]
