# Generated by Django 5.0.6 on 2024-05-24 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0006_rename_topic_message_topic_alter_message_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('date', models.DateField()),
                ('reference_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=100)),
                ('usd_opening_balance', models.FloatField()),
                ('zig_balance', models.FloatField()),
                ('usd_closing_balance', models.FloatField()),
                ('zig_closing_balance', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_api.bank_account')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('date', models.DateField()),
                ('reference_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=100)),
                ('usd_opening_balance', models.FloatField()),
                ('zig_balance', models.FloatField()),
                ('usd_closing_balance', models.FloatField()),
                ('zig_closing_balance', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_api.bank_account')),
            ],
        ),
    ]
