# Generated by Django 5.0.6 on 2024-05-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0007_deposits_withdrawals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Withdrawals',
            new_name='Deposit',
        ),
        migrations.RenameModel(
            old_name='Deposits',
            new_name='Withdrawal',
        ),
    ]
