# Generated by Django 5.0.6 on 2024-05-31 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0008_rename_withdrawals_deposit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='zig_balance',
            new_name='zig_opening_balance',
        ),
    ]
